"use client";

/**
 * Phase J — the "Scenarios" tab: §51's three-legged framework, §50's surprise
 * threshold, and the invalidation line, lifted onto their own surface.
 *
 * Phase F deliberately kept the scenarios INSIDE the Analysis tab, on the
 * grounds that a conditional must not be separated from the evidence backing
 * it. That reasoning still holds and this tab does not undo it — it re-renders
 * the same components from the same stored analysis, always labelled LLM,
 * always with the pointer back to the Analysis tab where the evidence is. What
 * it adds is a surface a trader can open at T-1 to read only the "what would
 * have to be true" list, without scrolling past six narrative sections first.
 *
 * Rules:
 *
 *  A. EVERYTHING ON THIS TAB IS MODEL OUTPUT, AND IT SAYS SO ONCE, LOUDLY.
 *     One LLM chip on the panel heading, not a chip per card: §49 asks that
 *     the tiers be separable on screen, and a tab that is ENTIRELY one tier is
 *     most honestly labelled at the boundary.
 *  B. NO PROBABILITIES, EVER — inherited from ScenarioCards, which owns that
 *     rule and is reused verbatim rather than reimplemented. A second
 *     scenario renderer would eventually grow a percentage.
 *  C. THE 404 IS THE ORDINARY FIRST VISIT. Nothing stored means no model has
 *     run for this event, which is the DEFAULT state of every event on this
 *     platform — generating costs money and is always an explicit action. It
 *     renders as a call-to-action pointing at the Analysis tab, which owns the
 *     Generate button. This tab has no Generate button of its own on purpose:
 *     two buttons that spend money are two places to audit.
 *  D. A STALE OR INVALID ANALYSIS IS STILL SHOWN, LABELLED. Hiding a scenario
 *     set because its number check failed would also hide that the check runs.
 */
import { useQuery } from "@tanstack/react-query";
import { api, isAnalysisNotFound } from "@/lib/api";
import { useT } from "@/lib/i18n";
import type { EventAnalysisPayload } from "@/lib/types";
import ScenarioCards from "./ScenarioCards";
import { TierChip } from "./EvidenceSections";
import {
  STATUS_BADGE_CLASS,
  hasViolations,
  isoStamp,
  narrativeText,
  regimeText,
  statusText,
  stringList,
  violationList,
} from "./analysis-format";

/** The render half, mounted directly by the tests with a fixed payload. */
export function ScenariosTabContent({
  data,
  notFound = false,
  errorMessage = null,
  onOpenAnalysis,
}: {
  data: EventAnalysisPayload | null | undefined;
  notFound?: boolean;
  errorMessage?: string | null;
  /** Jumps to the Analysis tab, which owns the Generate action. */
  onOpenAnalysis?: () => void;
}) {
  const t = useT();

  /* Rule C — the ordinary first visit, with its remedy attached. */
  if (notFound || (errorMessage == null && data?.analysis == null)) {
    return (
      <div className="panel" data-testid="scenarios-tab">
        <h2>
          {t("Scenarios", "情景")} <TierChip tier="LLM" />
        </h2>
        <p className="empty" data-testid="scenarios-cta">
          {t(
            "No analysis is stored for this event, so there are no scenarios to show. Scenarios are written by a language model over the evidence bundle, and generating one is always an explicit action because it spends a model call — the Analysis tab is where that button lives.",
            "本事件尚无已存储的分析,因此没有可展示的情景。情景由语言模型基于证据数据包撰写,而生成分析始终是一项显式操作 — 因为它会消耗一次模型调用;该按钮位于「分析」标签页。",
          )}
        </p>
        <p className="an-note">
          {t(
            "Nothing on this tab is ever generated by opening it. This page only reads what was already stored.",
            "打开本标签页绝不会生成任何内容。本页仅读取已存储的结果。",
          )}
        </p>
        {onOpenAnalysis != null && (
          <div className="row" style={{ marginTop: 12 }}>
            <button
              type="button"
              onClick={onOpenAnalysis}
              data-testid="scenarios-open-analysis"
            >
              {t("Open the Analysis tab", "打开「分析」标签页")}
            </button>
          </div>
        )}
      </div>
    );
  }

  if (errorMessage != null) {
    return (
      <div className="panel" data-testid="scenarios-tab">
        <h2>
          {t("Scenarios", "情景")} <TierChip tier="LLM" />
        </h2>
        {/* Verbatim server message. */}
        <p className="error" data-testid="scenarios-error">
          {t(
            `Could not load the stored analysis: ${errorMessage}`,
            `无法加载已存储的分析：${errorMessage}`,
          )}
        </p>
      </div>
    );
  }

  const analysis = data?.analysis ?? null;
  const status = data?.status ?? null;
  const badge = STATUS_BADGE_CLASS[status ?? ""] ?? "dim";
  const invalidation = narrativeText(analysis?.invalidation);
  const unknowns = stringList(analysis?.key_unknowns);
  const regime = regimeText(analysis?.expectations_gap_regime, t);
  const violations = violationList(data);

  return (
    <div className="panel" data-testid="scenarios-tab">
      <h2>
        {t("Scenarios", "情景")} <TierChip tier="LLM" />
      </h2>

      <div className="an-header-row">
        <span className={`badge ${badge}`} data-testid="scenarios-status">
          {statusText(status, t)}
        </span>
        {regime != null && (
          <span className="badge dim" data-testid="scenarios-regime">
            {regime}
          </span>
        )}
        {data?.cached === true && (
          <span className="badge dim">{t("CACHED", "缓存结果")}</span>
        )}
      </div>
      <p className="an-meta">
        <span className="k">{t("as of", "计算时点")}</span>{" "}
        <span className="mono" data-testid="scenarios-as-of">
          {isoStamp(data?.as_of) ?? "—"}
        </span>
        {" · "}
        <span className="k">{t("model", "模型")}</span>{" "}
        <span className="mono" data-testid="scenarios-model">
          {data?.provider ?? "—"}
          {data?.model != null && data.model !== "" ? `/${data.model}` : ""}
        </span>
      </p>

      {/* Rule D — a failed number check is shown, never silently dropped. */}
      {hasViolations(data) && (
        <div className="not-configured" role="status" data-testid="scenarios-violations">
          <p>
            <span className="badge red">{t("NUMBERS UNVERIFIED", "数字未通过校验")}</span>{" "}
            {t(
              "At least one number this analysis quoted did not reproduce against the evidence bundle. The scenarios are still shown — hiding them would also hide that the check runs — but read every figure below as unverified.",
              "本分析引用的数字中,至少有一个未能与证据数据包核对一致。情景内容仍予展示 — 若隐藏则连「校验机制存在」这一事实也会被一并隐藏 — 但请将以下所有数字视为未经核实。",
            )}
          </p>
          <ul className="an-violations">
            {violations.map((v, i) => (
              /* Verbatim validator findings (§47). */
              <li key={i} className="mono">
                {v}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Rule B — the one scenario renderer on the platform, reused. It carries
          the three fixed cards and the §50 surprise threshold with its
          not-a-probability note. */}
      <ScenarioCards analysis={analysis} />

      {/* §50 — "what would invalidate this?" is the part of an opinion that
          makes it checkable, so it rides with the scenarios rather than being
          left behind on the narrative tab: a conditional whose falsifier is on
          another screen is a conditional nobody checks. */}
      {invalidation != null && (
        <div className="an-prose-block" data-testid="scenarios-invalidation">
          <h3 className="an-h3">
            {t("What would invalidate this", "什么会推翻上述判断")}
          </h3>
          <p className="an-prose">{invalidation}</p>
        </div>
      )}

      {unknowns.length > 0 && (
        <div className="an-prose-block" data-testid="scenarios-unknowns">
          <h3 className="an-h3">{t("Key unknowns", "关键未知项")}</h3>
          <ul className="an-bullets">
            {unknowns.map((u, i) => (
              <li key={i}>{u}</li>
            ))}
          </ul>
        </div>
      )}

      <p className="an-note">
        {t(
          "Every word on this tab was written by a language model over the evidence bundle. The bundle itself — the measured half, with no model involved — is on the Evidence tab, and the full narrative is on the Analysis tab.",
          "本标签页的每一个字都由语言模型基于证据数据包撰写。证据数据包本身(不涉及任何模型的实测部分)位于「证据」标签页,完整叙述位于「分析」标签页。",
        )}
      </p>
      {onOpenAnalysis != null && (
        <div className="row" style={{ marginTop: 10 }}>
          <button
            type="button"
            onClick={onOpenAnalysis}
            data-testid="scenarios-open-analysis"
          >
            {t("Open the Analysis tab", "打开「分析」标签页")}
          </button>
        </div>
      )}
    </div>
  );
}

export default function ScenariosTab({
  eventId,
  asOf,
  onOpenAnalysis,
}: {
  eventId: number;
  asOf?: string;
  onOpenAnalysis?: () => void;
}) {
  const t = useT();
  // The SAME query key AnalysisTab uses, deliberately: it is the same GET with
  // the same arguments, so sharing the cache entry means opening this tab after
  // that one costs no request, and a regenerate over there invalidates here.
  const query = useQuery({
    queryKey: ["event-analysis", eventId, asOf ?? null],
    queryFn: () => api.events.analysis(eventId, asOf),
    enabled: Number.isFinite(eventId),
    // The 404 is the ordinary first visit; retrying it changes nothing.
    retry: (failureCount, error) => !isAnalysisNotFound(error) && failureCount < 1,
  });

  if (query.isLoading) {
    return (
      <div className="panel">
        <p className="empty">{t("Loading…", "加载中…")}</p>
      </div>
    );
  }

  const notFound = isAnalysisNotFound(query.error);
  return (
    <ScenariosTabContent
      data={query.data}
      notFound={notFound}
      errorMessage={!notFound && query.error != null ? query.error.message : null}
      onOpenAnalysis={onOpenAnalysis}
    />
  );
}
